# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: neuralops.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'neuralops.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fneuralops.proto\x12\tneuralops\"\x84\x04\n\tSpanProto\x12\x0f\n\x07span_id\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x16\n\x0eparent_span_id\x18\x03 \x01(\t\x12\x17\n\x0f\x63\x61usal_chain_id\x18\x04 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x05 \x01(\t\x12\x17\n\x0f\x61gent_framework\x18\x06 \x01(\t\x12\x14\n\x0cservice_name\x18\x07 \x01(\t\x12\x16\n\x0eoperation_name\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\x12\x15\n\rerror_message\x18\n \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x0b \x01(\x01\x12\r\n\x05model\x18\x0c \x01(\t\x12\x10\n\x08provider\x18\r \x01(\t\x12\x15\n\rprompt_tokens\x18\x0e \x01(\x03\x12\x19\n\x11\x63ompletion_tokens\x18\x0f \x01(\x03\x12\x14\n\x0ctotal_tokens\x18\x10 \x01(\x03\x12\x15\n\restimated_usd\x18\x11 \x01(\x01\x12\x1b\n\x13hallucination_score\x18\x12 \x01(\x01\x12\x1a\n\x12\x66\x61ithfulness_score\x18\x13 \x01(\x01\x12\x11\n\ttool_name\x18\x14 \x01(\t\x12\x12\n\nautonomous\x18\x15 \x01(\x08\x12\x17\n\x0f\x61ttributes_json\x18\x16 \x01(\t\x12\x15\n\rstarted_at_ms\x18\x17 \x01(\x03\"9\n\x12IngestBatchRequest\x12#\n\x05spans\x18\x01 \x03(\x0b\x32\x14.neuralops.SpanProto\"E\n\x0eIngestResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x05\x12\x10\n\x08rejected\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\x99\x01\n\x0fNeuralOpsIngest\x12G\n\x0bIngestBatch\x12\x1d.neuralops.IngestBatchRequest\x1a\x19.neuralops.IngestResponse\x12=\n\nIngestSpan\x12\x14.neuralops.SpanProto\x1a\x19.neuralops.IngestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neuralops_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPANPROTO']._serialized_start=31
  _globals['_SPANPROTO']._serialized_end=547
  _globals['_INGESTBATCHREQUEST']._serialized_start=549
  _globals['_INGESTBATCHREQUEST']._serialized_end=606
  _globals['_INGESTRESPONSE']._serialized_start=608
  _globals['_INGESTRESPONSE']._serialized_end=677
  _globals['_NEURALOPSINGEST']._serialized_start=680
  _globals['_NEURALOPSINGEST']._serialized_end=833
# @@protoc_insertion_point(module_scope)
