# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import neuralops_pb2 as neuralops__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in neuralops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NeuralOpsIngestStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestBatch = channel.unary_unary(
                '/neuralops.NeuralOpsIngest/IngestBatch',
                request_serializer=neuralops__pb2.IngestBatchRequest.SerializeToString,
                response_deserializer=neuralops__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestSpan = channel.unary_unary(
                '/neuralops.NeuralOpsIngest/IngestSpan',
                request_serializer=neuralops__pb2.SpanProto.SerializeToString,
                response_deserializer=neuralops__pb2.IngestResponse.FromString,
                _registered_method=True)


class NeuralOpsIngestServicer:
    """Missing associated documentation comment in .proto file."""

    def IngestBatch(self, request, context):
        """Ingest a batch of spans over gRPC (high-throughput alternative to HTTP)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestSpan(self, request, context):
        """Ingest a single span
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NeuralOpsIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestBatch,
                    request_deserializer=neuralops__pb2.IngestBatchRequest.FromString,
                    response_serializer=neuralops__pb2.IngestResponse.SerializeToString,
            ),
            'IngestSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestSpan,
                    request_deserializer=neuralops__pb2.SpanProto.FromString,
                    response_serializer=neuralops__pb2.IngestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neuralops.NeuralOpsIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neuralops.NeuralOpsIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NeuralOpsIngest:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neuralops.NeuralOpsIngest/IngestBatch',
            neuralops__pb2.IngestBatchRequest.SerializeToString,
            neuralops__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neuralops.NeuralOpsIngest/IngestSpan',
            neuralops__pb2.SpanProto.SerializeToString,
            neuralops__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
