apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuralops.fullname" . }}-secrets
  labels:
    {{- include "neuralops.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-url: {{ .Values.externalSecrets.redis.url | quote }}
  postgres-url: {{ .Values.externalSecrets.postgres.url | quote }}
  groq-api-key: {{ .Values.llmProviders.groq.apiKey | quote }}
  mistral-api-key: {{ .Values.llmProviders.mistral.apiKey | quote }}
  openrouter-api-key: {{ .Values.llmProviders.openrouter.apiKey | quote }}
